### ISSUE TITLE
arborean-apparel not loaded

### ISSUE THREAD

**Issue by Fukki** [Mathicha/arborean-apparel#1]
after update this module not loaded in proxy.
when i try to change costume then relogin or change map the costume not showed.
it only show in lobby.

only this old https://github.com/Mathicha/arborean-apparel/tree/daeb2e98ced670ec9abb77c6c4e037df49406404 has fine.

**Comment by Mathicha** [comment]
I think it don't load because you are using an **outdated** proxy that does not support bigint

**Comment by Mathicha** [comment]
update: it's now compatible with caali's proxy
